#!/bin/sh

basedir="$1"
test -z "$basedir" && basedir=$(pwd)

cat_name_files() {
	echo "*.[ch] *.py *.cc *.cpp *.html *.inc *.css *.js *.asp *.dts *.dtsi *.lua *.sh *.lua *.S *.html *.htm *.js Kconfig Makefile" | sed -n '
		/[^[:space:]]\+[[:space:]]\+/ {
			s/\([^[:space:]]*\)[[:space:]]\+/-name "\1" -or /g
		}
		/[^[:space:]]\+$/ {
			s/\([^[:space:]]\+\)$/-name "\1"/g
		}

		p
	'
}

find_source() {
	FILES=$(cat_name_files)
	eval "find ! \\( -name .svn -o -name tmp-glibc -o -name html -prune \\) -readable -type f \\( $FILES \\)"
}

bail() {
	echo "$*" >&2
	exit 1
}

echo "* finding source files to cscope.files"
find_source | tee cscope.files || bail "failed in finding files"

echo "* build cscope"
#cscope -buvq
cscope -buv
readlink -f cscope.out
