#!/bin/bash

# bash settings
set -o vi

# alias
alias clipboard="xsel --clipboard"
alias m='source /usr/lib/mc/mc-wrapper.sh --nomouse'
alias fd='fdfind -IHp'

# editors
export SVN_EDITOR=vi
export VISUAL=vim
export EDITOR="$VISUAL"

PS1='[${debian_chroot:+($debian_chroot)}\[\033[01;34m\]\W\[\033[00m\]]\$ '
