#!/bin/bash

#text_red=$(tput setaf 1)
#text_green=$(tput setaf 2)
#text_blue=$(tput setaf 4)
text_magenta=$(tput setaf 5)
#text_yellow=$(tput setaf 3)
text_bold=$(tput bold)
#text_rev=$(tput rev)
text_reset=$(tput sgr0)

sed_remove_index() {
    sed -r 's/^[[:space:]]*[0-9]+[[:space:]]+//g'
}

sed_exclude_0_index() {
    sed -r "/^[[:space:]]*0[[:space:]]+/d"
}

smart_pwd() {
    echo "$PWD" | sed -r "s#^$HOME($|/)#~\1#g"
}

smart_pwd_escaped() {
    smart_pwd | sed -r 's/\(/\\(/g;s/\)/\\)/g;'
}

smart_popd() {
    for i in $(dirs -v | sort -rn -k 1 | sed -rn "s#^[[:space:]]*([1-9]+[0-9]*)[[:space:]]+$(smart_pwd_escaped)\$#\1#p"); do
        popd -n "+$i" >/dev/null
    done
}

sed_pushd() {
    sed -rn 's#(.*)#pushd -n "\1" > /dev/null#p' "$@"
}

smart_history_update() {
    # push current directory
    smart_popd
    pushd -n "$(smart_pwd)" >/dev/null

    # merge memory history into stored history
    (
        dirs -v | sed_remove_index
        cat ~/.dirstack 2>/dev/null
    ) | sort -ur >~/.dirstack.$$
    mv -f ~/.dirstack.$$ ~/.dirstack

    # load stored history
    dirs -c
    # shellcheck source=/dev/null
    source <(sed_pushd ~/.dirstack 2>/dev/null)
}

smart_history_show() {

    echo ""
    echo "${text_bold}##### mc$text_reset"
    dirs_from_mc | sed -r "s#^(${PWD}$)\$#$text_magenta\1*$text_reset#g;"
    echo ""
    echo "${text_bold}###### stack$text_reset"
    dirs -v | sed_exclude_0_index | sed -r 's/^ ([0-9] )/\1  /g;s/^([0-9][0-9] )/\1 /g;' | sed -rn "s#^([[:space:]]*)([1-9]+[0-9]*)([[:space:]]+)(.*)\$#\1\2\3\4 [\2]#p;" | sort -u -k 2 |
        sed -r "s#^([[:space:]]*[0-9]+[[:space:]]+$(smart_pwd_escaped)[[:space:]]+\[[0-9]+\])\$#$text_magenta\1*$text_reset#g;"

    echo ""
}

smart_seq() {
    eval "$(
        sed -rn '
            /^([0-9]+)-([0-9]+)$/ {
                s/^([0-9]+)-([0-9]+)$/seq \1 \2;/p
            }

            /^([0-9]+)$/ {
                s/^([0-9]+)$/echo \1;/p
            }
        '
    )"
}

egrep_pwd() {
    _pwd=$(smart_pwd_escaped)
    grep -E "$@" "^[[:space:]]*[0-9]+[[:space:]]+${_pwd}\$"
}

dirsv_without_0_index() {
    dirs -v | sed_exclude_0_index | egrep_pwd -v
}

dirs_from_mc() {
    sed -rn 's/.*URL "([^"]+)".*/\1/p' ~/.config/mc/hotlist | grep -v "//" | sort -u
}

dirs_from_mc_without_pwd() {
    dirs_from_mc | grep -Ev "^${PWD}$"
}

sed_dir_only() {
    head -n 1 | sed -rn "s#^([[:space:]]*)([1-9]+[0-9]*)([[:space:]]+)(.*)\$#\4#p;"
}

print_parent_dirs() {
    (
        smart_pwd
        while true; do
            if [ "x$PWD" = "x/" ]; then
                break
            fi

            cd .. 2>/dev/null
            smart_pwd
        done
    )
}

smart_cd() {
    cdir=""
    if [ "$#" -eq 0 ]; then
        #smart_wcd . > /dev/null
        smart_history_show
        return 0
    elif [ "x$1" = "x!" ]; then
        shift

        rm -f ~/.dirstack*

        if [ "$#" -eq 0 ]; then
            dirs -c
        else
            re='(^[0-9]+$|^[0-9]+-[0-9]+$)'
            for j in "$@"; do

                if [[ "$j" =~ $re ]]; then
                    for i in $(echo "$j" | tr ' ' '\n' | smart_seq | sort -rn); do
                        echo "delete $(dirs "+$i")"
                        popd -n "+$i" >/dev/null
                    done
                else
                    for i in $(dirsv_without_0_index | grep -E "$j" | sed -rn 's/^[[:space:]]*([0-9]+).*/\1/p' | sort -rn); do
                        echo "delete $(dirs "+$i")"
                        popd -n "+$i" >/dev/null
                    done
                fi
            done
        fi

        smart_history_update
        return 0

    elif [ -e "$1" ] && [ ! -d "$1" ]; then
        eval /usr/bin/wcd.exec -i -q -c "$(dirname "$1")" || return $?
    else
        if [ "$1" = '=' ] || [ "$1" = '-' ] || [ "$1" = '+' ] || [ "${1}" = ".." ] || [ "${1}" = "." ]; then
            cdir="$1"
        elif (cd "$@") 2>/dev/null; then
            sdir=""
        else
            sdir=""
            # search for index
            test -n "$sdir" || sdir=$(dirsv_without_0_index | grep -E "^[[:space:]]*$*[[:space:]]+" | sed_dir_only)
            # search for parent
            test -n "$sdir" || sdir=$(print_parent_dirs | sort | agrep -B -i "$*[^/]*$" | sed_dir_only)
            test -n "$sdir" || sdir=$(print_parent_dirs | sort | agrep -B -i "$*" | sed_dir_only)
            # search for mc
            test -n "$sdir" || sdir=$(dirs_from_mc_without_pwd | sort | agrep -B -i "$*[^/]*$")
            test -n "$sdir" || sdir=$(dirs_from_mc_without_pwd | sort | agrep -B -i "$*")
            # search for history
            test -n "$sdir" || sdir=$(dirsv_without_0_index | agrep -B -i "$*[^/]*$" | sed_dir_only)
            test -n "$sdir" || sdir=$(dirsv_without_0_index | agrep -B -i "$*" | sed_dir_only)

            # while read -r i; do
            #     test -n "$sdir" || sdir=$(dirsv_without_0_index | grep -E -i "$i/.*/$*$" | sed_dir_only)
            #     test -n "$sdir" || sdir=$(dirsv_without_0_index | grep -E -i "$i/.*/$*" | sed_dir_only)
            #     test -n "$sdir" || sdir=$(dirsv_without_0_index | grep -E -i "$i/.*$*" | sed_dir_only)
            # done < <(print_parent_dirs)

            # test -n "$sdir" || sdir=$(dirsv_without_0_index | grep -E -i "/$*$" | sed_dir_only)
            # test -n "$sdir" || sdir=$(dirsv_without_0_index | grep -E -i "/$*" | sed_dir_only)
            # test -n "$sdir" || sdir=$(dirsv_without_0_index | grep -E -i "$*" | sed_dir_only)
        fi

        sdir=${sdir/#~\//$HOME\/}

        if [ -z "$cdir" ]; then
            /usr/bin/wcd.exec -i -q -c "${sdir:-$*}" || return $?
        fi
    fi

    if [ -z "$cdir" ]; then
        grep -q "cd" ~/bin/wcd.go 2>/dev/null || return $?
        # shellcheck source=/dev/null
        source ~/bin/wcd.go || return $?
    else
        cd "$cdir" || bail "failed to cd to $cdir"
    fi

    if [ -t 1 ]; then
        smart_history_update
        echo "$text_magenta== [cd] $(dirs -v | sed_exclude_0_index | egrep_pwd | sed -rn "s#^([[:space:]]*)([1-9]+[0-9]*)([[:space:]]+)(.*)\$#\1\2\3\4 [\2]#p;") ==$text_reset"
    fi

    #echo -ne "\033]30;$(basename $(pwd))\007"

    return $?
}

# bash settings
set -o vi

#######################################################################################################################
# alias
#######################################################################################################################

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    # shellcheck disable=SC2015
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"

    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

alias cb="xsel --clipboard"
alias m='source /usr/lib/mc/mc-wrapper.sh --nomouse'
alias c='smart_cd'

smart_history_update
