#!/bin/bash

untar.tar.7z() {
    7z x -so "$1" | tar xf - -C "$2"
}

untar.tar.gz() {
    tar -xf "$1" -C "$2"
}

untar.zip() {
    (cd "$2" && unzip -o "../$1")
}

untar.7z() {
    (cd "$2" && 7z x "../$1")
}


extentions=(".tar.7z" ".tar.gz" ".zip" ".7z")

while read -u 10 fname; do
    for ext in "${extentions[@]}"; do
        dir=${fname/%${ext}/}
        if [ "${fname}" != "${dir}" ]; then
            mkdir -p "$dir" 2> /dev/null
            echo "========================================= [unzip] '$fname' ===>  '$dir'"
            if ! untar${ext} "$fname" "$dir"; then
                echo "failed to untar (fname=${fname},ext=${ext})"
                exit 0
            fi

            rm -f "$fname"
            break

        fi
    done
done 10< <(ls ${extentions[@]/#/*})
